# Generated by Django 2.1.4 on 2019-01-02 17:30

from django.db import migrations, models
import likert_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikertModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_is_the_best', likert_field.models.LikertField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_cream_is_yummy', likert_field.models.LikertField(blank=True, null=True)),
                ('item', likert_field.models.LikertField(blank=True, null=True, verbose_name='ice cream beats cabbage')),
                ('questions_should_not_be_optional', likert_field.models.LikertField(blank=True, null=True)),
            ],
        ),
    ]
